name: ESLint

on:
  push:
    paths:
      - '**/*.vue'
      - '**/*.ts'
  pull_request:
    paths:
      - '**/*.vue'
      - '**/*.ts'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run lint
